// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhmdjzfxtusywgozzgmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobWRqemZ4dHVzeXdnb3p6Z21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTIyMTcsImV4cCI6MjA2NDUyODIxN30.OmH2ojCGwClGEOlpWIz3hc8oBpBvROtelOxAFcTVUpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);